// Generated by CoffeeScript 1.6.3
(function() {
  var ctx, drawBrick;

  ctx = $('#game')[0].getContext('2d');

  drawBrick = function(x, y) {
    return ctx.fillRect((x - 1) * 40 + 2, (y - 1) * 40 + 2, 38, 38);
  };

}).call(this);
