// Generated by CoffeeScript 1.6.3
(function() {
  var clearScreen, ctx, drawBrick, drawLine, pos, rot;

  ctx = $('#game')[0].getContext('2d');

  drawBrick = function(x, y) {
    return ctx.fillRect((x - 1) * 40 + 2, (y - 1) * 40 + 2, 38, 38);
  };

  drawLine = function(x, y, rot) {
    if (!(rot % 2)) {
      drawBrick(x, y - 1);
      drawBrick(x, y);
      drawBrick(x, y + 1);
      return drawBrick(x, y + 2);
    } else {
      drawBrick(x - 1, y);
      drawBrick(x, y);
      drawBrick(x + 1, y);
      return drawBrick(x + 2, y);
    }
  };

  clearScreen = function() {
    return ctx.clearRect(0, 0, 400, 800);
  };

  pos = 1;

  rot = 0;

  setInterval(function() {
    clearScreen();
    drawLine(5, pos, rot);
    pos += 1;
    return rot += 1;
  }, 1000);

}).call(this);
