// Generated by CoffeeScript 1.6.3
(function() {
  var clearScreen, ctx, drawBrick, drawLine, drawRL, test;

  ctx = $('#game')[0].getContext('2d');

  drawBrick = function(x, y) {
    return ctx.fillRect((x - 1) * 40 + 2, (y - 1) * 40 + 2, 38, 38);
  };

  drawLine = function(x, y, rot) {
    ctx.fillStyle = "#48f";
    if (!(rot % 2)) {
      drawBrick(x, y - 1);
      drawBrick(x, y);
      drawBrick(x, y + 1);
      return drawBrick(x, y + 2);
    } else {
      drawBrick(x - 1, y);
      drawBrick(x, y);
      drawBrick(x + 1, y);
      return drawBrick(x + 2, y);
    }
  };

  drawRL = function(x, y, rot) {
    ctx.fillStyle = "#00f";
    if (rot % 4 === 0) {
      drawBrick(x, y + 1);
      drawBrick(x, y);
      drawBrick(x, y - 1);
      drawBrick(x + 1, y - 1);
    }
    if (rot % 4 === 1) {
      drawBrick(x - 1, y);
      drawBrick(x, y);
      drawBrick(x + 1, y);
      drawBrick(x + 1, y + 1);
    }
    if (rot % 4 === 2) {
      drawBrick(x, y - 1);
      drawBrick(x, y);
      drawBrick(x, y + 1);
      drawBrick(x - 1, y + 1);
    }
    if (rot % 4 === 3) {
      drawBrick(x - 1, y - 1);
      drawBrick(x - 1, y);
      drawBrick(x, y);
      return drawBrick(x + 1, y);
    }
  };

  clearScreen = function() {
    return ctx.clearRect(0, 0, 400, 800);
  };

  test = function(f) {
    var pos, rot;
    pos = 2;
    rot = 0;
    return setInterval(function() {
      clearScreen();
      f(5, pos, rot);
      if (rot % 5 === 4) {
        pos += 1;
      }
      rot += 1;
      if (pos === 20) {
        return pos = 2;
      }
    }, 500);
  };

  test(drawLine);

}).call(this);
